const { Router} = require('express')
const authController = require('../controllers/authController')
const {verifyAuth, checkStock, upload} = require('../middlewares/authMiddleware')
router = Router()

router.get('/signup', authController.signup_get)
router.post('/signup', authController.signup_post)
router.get('/login', authController.login_get)
router.post('/login', authController.login_post)
router.get('/logout', authController.logout_get)
router.get('/categories/:category', authController.category)
router.get('/catalogue', authController.catalogue)
router.get('/search', authController.search_get)
router.get('/inputitem', authController.add_get)
router.post('/inputitem',upload.single('image'), authController.add_post)
router.get('/item/:itemid', authController.item_get)
router.use('/cart', checkStock)
router.post('/cart', authController.addCart)
router.get('/cart', authController.cart)
router.put('/cart', authController.modifyCart)
router.delete('/cart', authController.removeItem)
router.get('/cartapi', authController.getUpdatedCart)
router.get('/cart/checkout', authController.checkout_get)
router.delete('/cart/checkout', authController.checkout)
router.get('/purchase', authController.purchase)
router.get('/contact', authController.contact)
router.post('/contact', authController.contact_post)
module.exports = router;
// fields([{name: 'itemname'}, {name: 'category'}, {name: 'price'}, {name: 'quantity'}, {name: 'image'}])