const { Router} = require('express')
const authController = require('../controllers/authController')
const {verifyAuth,verifyAdmin, checkStock, upload} = require('../middlewares/authMiddleware')
router = Router()

router.get('/signup', authController.signup_get)
router.post('/signup', authController.signup_post)
router.get('/login', authController.login_get)
router.post('/login', authController.login_post)
router.get('/logout', authController.logout_get)
router.use(['/admin/user', '/admin/item'], verifyAdmin)
router.get('/admin/login', authController.adminlogin)
router.post('/admin/login', authController.adminlogin_post)
router.get('/admin/user', authController.adminuser)
router.get('/admin/item', authController.adminitem)
router.get('/admin/order', authController.adminorder)
router.get('/admin/item/details/:itemid', authController.adminitemdesc)
router.get('/admin/user/details/:userid', authController.adminuserdesc)
router.get('/categories/:category', authController.category)
router.get('/catalogue', authController.catalogue)
router.get('/search', authController.search_get)
router.get('/admin/item/inputitem', authController.add_get)
router.post('/admin/item/inputitem',upload.single('image'), authController.add_post)
router.put('/admin/item/updateitem', authController.updateitem)
router.put('/admin/item/updateitemimg',upload.single('image'), authController.updateitemimg)
router.delete('/admin/item/deleteitem', authController.deleteitem)
router.put('/admin/user/updateuser', authController.updateuser)
router.delete('/admin/user/deleteuser', authController.deleteuser)
router.put('/admin/order/updateorder', authController.updatestatus)
router.delete('/admin/order/deleteorder', authController.deleteorder)
router.get('/adminlogout', authController.admin_logout)
router.get('/item/:itemid', authController.item_get)
router.use('/cart', checkStock)
router.get('/profile', authController.profile)
router.put('/profile', authController.profile_update)
router.post('/cart', authController.addCart)
router.get('/cart', authController.cart)
router.put('/cart', authController.modifyCart)
router.delete('/cart', authController.removeItem)
router.get('/cartapi', authController.getUpdatedCart)
router.get('/cart/checkout', authController.checkout_get)
router.delete('/cart/checkout', authController.checkout)
router.get('/purchase', authController.purchase)
router.get('/purchase/:purchaseid', authController.purchasedesc)
router.put('/purchase/uploadtransfer',upload.single('image'), authController.uploadtransfer)
router.get('/contact', authController.contact)
router.post('/contact', authController.contact_post)
module.exports = router;
// fields([{name: 'itemname'}, {name: 'category'}, {name: 'price'}, {name: 'quantity'}, {name: 'image'}])