const { Router} = require('express')
const mainController = require('../controllers/mainController')
const {verifyAuth,verifyAdmin, checkStock, upload} = require('../middlewares/mainMiddleware')
router = Router()

router.get('/signup', mainController.signup_get)
router.post('/signup', mainController.signup_post)
router.get('/login', mainController.login_get)
router.post('/login', mainController.login_post)
router.get('/logout', mainController.logout_get)
router.use(['/admin/user', '/admin/item'], verifyAdmin)
router.get('/admin/login', mainController.adminlogin)
router.post('/admin/login', mainController.adminlogin_post)
router.get('/admin/user', mainController.adminuser)
router.get('/admin/item', mainController.adminitem)
router.get('/admin/order', mainController.adminorder)
router.get('/admin/item/details/:itemid', mainController.adminitemdesc)
router.get('/admin/user/details/:userid', mainController.adminuserdesc)
// router.get('/categories/:category', mainController.category)
router.get('/catalogue', mainController.catalogue)
// router.get('/search', mainController.search_get)
router.get('/admin/item/inputitem', mainController.add_get)
router.post('/admin/item/inputitem',upload.single('image'), mainController.add_post)
router.put('/admin/item/updateitem', mainController.updateitem)
router.put('/admin/item/updateitemimg',upload.single('image'), mainController.updateitemimg)
router.delete('/admin/item/deleteitem', mainController.deleteitem)
router.put('/admin/user/updateuser', mainController.updateuser)
router.delete('/admin/user/deleteuser', mainController.deleteuser)
router.put('/admin/order/updateorder', mainController.updatestatus)
router.delete('/admin/order/deleteorder', mainController.deleteorder)
router.get('/adminlogout', mainController.admin_logout)
router.get('/item/:itemid', mainController.item_get)
router.use('/cart', checkStock)
router.get('/profile', mainController.profile)
router.put('/profile', mainController.profile_update)
router.post('/cart', mainController.addCart)
router.get('/cart', mainController.cart)
router.put('/cart', mainController.modifyCart)
router.delete('/cart', mainController.removeItem)
router.get('/cartapi', mainController.getUpdatedCart)
router.get('/cart/checkout', mainController.checkout_get)
router.delete('/cart/checkout', mainController.checkout)
router.get('/purchase', mainController.purchase)
router.get('/purchase/:purchaseid', mainController.purchasedesc)
router.put('/purchase/uploadtransfer',upload.single('image'), mainController.uploadtransfer)
router.get('/contact', mainController.contact)
router.post('/contact', mainController.contact_post)
module.exports = router;
// fields([{name: 'itemname'}, {name: 'category'}, {name: 'price'}, {name: 'quantity'}, {name: 'image'}])